[project]
name = "caiman-tools"
dynamic = ["version"]
description = "CLI tools for batch-processing calcium imaging movies with CaImAn."
readme = "README.md"
authors = [
    { name = "Christoph Sommer", email = "christoph.sommer@ist.ac.at" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "loguru",
]

[project.scripts]
caiman-cnmfe = "caiman_tools.cli:main"
caiman-view = "caiman_tools.cli_view:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/caiman_tools/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/caiman_tools"]
