[project]
name = "caiman-tools"
version = "0.1.0"
description = "CLI tools for batch-processing calcium imaging movies with CaImAn."
readme = "README.md"
authors = [
    { name = "Christoph Sommer", email = "christoph.sommer@ist.ac.at" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "loguru",
]

[project.scripts]
caiman-cnmfe = "caiman_tools.cli:main"
caiman-view = "caiman_tools.cli_view:main"

[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"
